### ISSUE TITLE
localstack:stop doesn't always run, leaving behind a running BrowserStackLocal process

### ISSUE THREAD

**Issue by discopatrick** [lucasfeliciano/grunt-localstack#1]
Hi @lucasfeliciano 

Good work on this grunt task! Was just what I was looking for.

However, I'm finding that if there is any sort of problem (e.g. failed PHPUnit test) in between running 'localstack' and 'localstack:stop', then the latter will not run, and the BrowserStackLocal process is left running. This in turn will prevent any further runs of the task - I think BrowserStack gets confused by multiple connections.

Not sure if this is a problem with your task, or the node module it is based on?

**Comment by lucasfeliciano** [comment]
So, that is the expected behaviour of grunt. If a job fails grunt exit the process and do not execute the others tasks in the chain.

To get around that you can use this module: https://github.com/pghalliday/grunt-continue
Using grunt-continue plugin you can force other tasks to continue after failures.

Sorry for the delay to answer you, I didn't noticed the notification in my email.

**Comment by discopatrick** [comment]
Thanks @lucasfeliciano - your answer is much appreciated.

**Comment by sharadJay** [comment]
Hi I am still observing this issue, I get following message when I run grunt localstack:stop

```
Running "localstack:stop" task
Warning: undefined is not a function Use --force to continue.

Aborted due to warnings.
```
